/*
 * Copyright Red Hat, Inc. and/or its affiliates
 * and other contributors as indicated by the @author tags and
 * the COPYRIGHT.txt file distributed with this work.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.teiid.stateservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.6-patch-01
 * Wed Jan 19 13:44:29 EST 2011
 * Generated source version: 2.2.6-patch-01
 * 
 */

@WebFault(name = "GetStateInfoFault", targetNamespace = "http://www.teiid.org/stateService/")
public class GetStateInfoFault_Exception extends Exception {
    public static final long serialVersionUID = 20110119134429L;
    
    private org.teiid.stateservice.jaxb.GetStateInfoFault getStateInfoFault;

    public GetStateInfoFault_Exception() {
        super();
    }
    
    public GetStateInfoFault_Exception(String message) {
        super(message);
    }
    
    public GetStateInfoFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public GetStateInfoFault_Exception(String message, org.teiid.stateservice.jaxb.GetStateInfoFault getStateInfoFault) {
        super(message);
        this.getStateInfoFault = getStateInfoFault;
    }

    public GetStateInfoFault_Exception(String message, org.teiid.stateservice.jaxb.GetStateInfoFault getStateInfoFault, Throwable cause) {
        super(message, cause);
        this.getStateInfoFault = getStateInfoFault;
    }

    public org.teiid.stateservice.jaxb.GetStateInfoFault getFaultInfo() {
        return this.getStateInfoFault;
    }
}
